/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Ward1RouteImport } from './routes/ward-1'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PrioritiesRouteImport } from './routes/priorities'
import { Route as NewhomeRouteImport } from './routes/newhome'
import { Route as MeetDoritRouteImport } from './routes/meet-dorit'
import { Route as GetInvolvedRouteImport } from './routes/get-involved'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as IndexRouteImport } from './routes/index'

const Ward1Route = Ward1RouteImport.update({
  id: '/ward-1',
  path: '/ward-1',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrioritiesRoute = PrioritiesRouteImport.update({
  id: '/priorities',
  path: '/priorities',
  getParentRoute: () => rootRouteImport,
} as any)
const NewhomeRoute = NewhomeRouteImport.update({
  id: '/newhome',
  path: '/newhome',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetDoritRoute = MeetDoritRouteImport.update({
  id: '/meet-dorit',
  path: '/meet-dorit',
  getParentRoute: () => rootRouteImport,
} as any)
const GetInvolvedRoute = GetInvolvedRouteImport.update({
  id: '/get-involved',
  path: '/get-involved',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/get-involved': typeof GetInvolvedRoute
  '/meet-dorit': typeof MeetDoritRoute
  '/newhome': typeof NewhomeRoute
  '/priorities': typeof PrioritiesRoute
  '/privacy': typeof PrivacyRoute
  '/ward-1': typeof Ward1Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/get-involved': typeof GetInvolvedRoute
  '/meet-dorit': typeof MeetDoritRoute
  '/newhome': typeof NewhomeRoute
  '/priorities': typeof PrioritiesRoute
  '/privacy': typeof PrivacyRoute
  '/ward-1': typeof Ward1Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/get-involved': typeof GetInvolvedRoute
  '/meet-dorit': typeof MeetDoritRoute
  '/newhome': typeof NewhomeRoute
  '/priorities': typeof PrioritiesRoute
  '/privacy': typeof PrivacyRoute
  '/ward-1': typeof Ward1Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/community'
    | '/contact'
    | '/donate'
    | '/get-involved'
    | '/meet-dorit'
    | '/newhome'
    | '/priorities'
    | '/privacy'
    | '/ward-1'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/community'
    | '/contact'
    | '/donate'
    | '/get-involved'
    | '/meet-dorit'
    | '/newhome'
    | '/priorities'
    | '/privacy'
    | '/ward-1'
  id:
    | '__root__'
    | '/'
    | '/community'
    | '/contact'
    | '/donate'
    | '/get-involved'
    | '/meet-dorit'
    | '/newhome'
    | '/priorities'
    | '/privacy'
    | '/ward-1'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommunityRoute: typeof CommunityRoute
  ContactRoute: typeof ContactRoute
  DonateRoute: typeof DonateRoute
  GetInvolvedRoute: typeof GetInvolvedRoute
  MeetDoritRoute: typeof MeetDoritRoute
  NewhomeRoute: typeof NewhomeRoute
  PrioritiesRoute: typeof PrioritiesRoute
  PrivacyRoute: typeof PrivacyRoute
  Ward1Route: typeof Ward1Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ward-1': {
      id: '/ward-1'
      path: '/ward-1'
      fullPath: '/ward-1'
      preLoaderRoute: typeof Ward1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/priorities': {
      id: '/priorities'
      path: '/priorities'
      fullPath: '/priorities'
      preLoaderRoute: typeof PrioritiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newhome': {
      id: '/newhome'
      path: '/newhome'
      fullPath: '/newhome'
      preLoaderRoute: typeof NewhomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meet-dorit': {
      id: '/meet-dorit'
      path: '/meet-dorit'
      fullPath: '/meet-dorit'
      preLoaderRoute: typeof MeetDoritRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-involved': {
      id: '/get-involved'
      path: '/get-involved'
      fullPath: '/get-involved'
      preLoaderRoute: typeof GetInvolvedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommunityRoute: CommunityRoute,
  ContactRoute: ContactRoute,
  DonateRoute: DonateRoute,
  GetInvolvedRoute: GetInvolvedRoute,
  MeetDoritRoute: MeetDoritRoute,
  NewhomeRoute: NewhomeRoute,
  PrioritiesRoute: PrioritiesRoute,
  PrivacyRoute: PrivacyRoute,
  Ward1Route: Ward1Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
